name: Refresh and Run Every 10 Minutes

on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  refresh_and_run:
    runs-on: ubuntu-latest
    steps:
      - name: Send HTTP request
        uses: wei/curl@v1
        with:
          args: http://live.idesignix.com/hls/scrap/extractchannels/alwaysdomain.php
