name: Refresh and Run

on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  refresh_and_run:
    runs-on: ubuntu-latest
    steps:
      - name: Send HTTP request
        uses: wei/curl@v1
        with:
          args: https://u.idesignix.com/alwaysdo
